[doc]
name = "planificacion"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "output"
type = "pdf"
tex_format = "latex"
shell_escape_cwd = "src"
index = "main.tex"

